# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_base_version=26.1.2
minecraft_version=26.1.2
# Minecraft 26.1+ ships unobfuscated and no longer uses a mappings dependency
loader_version=0.19.3

# Mod Properties
mod_version=0.3.0
maven_group=com.glisco
archives_base_name=buildup-interactic

# Dependencies
fabric_version=0.155.2+26.1.2
yacl_version=3.9.6+26.1-fabric

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version = 18.0.0

